name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run buildpro
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: ./public
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NAME_CALENDAR_123 }}"
          channelId: live
          projectId: name-calendar-123
