name: Build project
'on':
  push:
    branches:
      - master
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Build
        run: npm run buildpro
